name: eShopOnWeb Build and Test

#Triggers (uncomment line below to use it)
on: [push, workflow_dispatch]

#Environment variables https://docs.github.com/en/actions/learn-github-actions/environment-variables
env:
  RESOURCE-GROUP: rg-eshoponweb-trainer
  LOCATION: eastus
  TEMPLATE-FILE: infra/webapp.bicep
  SUBSCRIPTION-ID: ${{ secrets.AZURE_CREDENTIALS.subscriptionId }}
  WEBAPP-NAME: eshoponweb-webapp-student-2

jobs:
  # Build, test and publish .net web project in repository
  buildandtest:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - uses: actions/checkout@v4
    
    # Prepare runner for desired .NET version SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        dotnet-quality: 'preview'
        
    # Build/Test/Publish the .NET project
    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Release
    - name: Test with dotnet
      run: dotnet test ./eShopOnWeb.sln --configuration Release
    - name: dotnet publish
      run: |
        dotnet publish ./src/Web/Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
        cd ${{env.DOTNET_ROOT}}/myapp
        zip -r ../app.zip .
        
    # Upload the published website code artifacts
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/app.zip
        
    # Upload the Bicep template as artifacts for the next job
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: bicep-template
        path: ${{ env.TEMPLATE-FILE }}

  # Use Bicep to deploy infrastructure + Publish webapp 
  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: 'Development'
    steps:
    
    # Download the published files created in the previous job
    - name: Download artifact for deployment job (.net-app)
      uses: actions/download-artifact@v4
      with:
        name: .net-app
        path: .net-app
  
    # Download the Bicep templates from the previous job
    - name: Download artifact for deployment job (bicep-template)
      uses: actions/download-artifact@v4
      with:
        name: bicep-template
        path: bicep-template
        
    # Login to Azure using Service Principal
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      continue-on-error: false # Stop the workflow if login fails
     
    # Debugging: Add a step to verify if the login was successful
    - name: Verify Azure Login
      run: az account show
    
    # Template Validation (using Azure CLI)
    - name: Validate Azure Bicep Template
      run: |
        az deployment group validate \
          --resource-group ${{ env.RESOURCE-GROUP }} \
          --template-file bicep-template/webapp.bicep \
          --parameters webAppName=${{ env.WEBAPP-NAME }} location=${{ env.LOCATION }}
    
    # Deploy Azure WebApp using Bicep file
    - name: Deploy Azure WebApp using Bicep file
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ env.SUBSCRIPTION-ID }}
        resourceGroupName: ${{ env.RESOURCE-GROUP }}
        template: bicep-template/webapp.bicep
        parameters: |
          webAppName=${{ env.WEBAPP-NAME }}
          location=${{ env.LOCATION }}
        failOnStdErr: true  # Ensure that any errors in stderr will fail the deployment

    # Publish website to Azure App Service using CLI (WebApp)
    - name: Publish Website to WebApp (CLI)
      uses: Azure/cli@v2
      with:
        inlineScript: |
          az webapp deploy --name ${{ env.WEBAPP-NAME }} --resource-group ${{ env.RESOURCE-GROUP }} --src-path .net-app/app.zip --type zip
